name: Building recovery

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  workflow_dispatch:

env:
  MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-12.1
  DEVICE: m14x
  DT_LINK: https://github.com/adrall12/android_device_samsung_m14x
  DT_PATH: device/samsung/m14x
  TARGET: bootimage
  TZ: Asia/manila

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
         

       - name: Initializing environment
         run: |
            dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
            df -h
            sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel
            sudo apt-get autoremove -y
            sudo apt-get clean
            df -h
            echo "Removing large directories"
            rm -rf /usr/share/dotnet/
            df -h
            sudo rm -rf /usr/share/dotnet
            sudo rm -rf /opt/ghc
            sudo rm -rf "/usr/local/share/boost"
            sudo rm -rf "$AGENT_TOOLSDIRECTORY"
            sudo apt install software-properties-common -y
            sudo add-apt-repository http://cz.archive.ubuntu.com/ubuntu jammy main multiverse
            sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
            docker rmi `docker images -q`
            git config --global user.name "mastersenpai05"
            git config --global user.email "pampangavergil0405@gmail.com"
            sudo apt update
            sudo apt install bc build-essential zip curl libstdc++6 git wget python3 gcc clang libssl-dev repo rsync flex curl  bison aria2
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo
            
       - name: Sync recovery source and device tree
         run: |
             mkdir work
             cd work
             repo init -u $MANIFEST --depth=1
             repo sync -c -j4 --force-sync --no-clone-bundle --no-tags
             repo sync -c -j4 --force-sync --no-clone-bundle --no-tags
             git clone --depth=1 $DT_LINK $DT_PATH
             
       - name: Build
         run: |
              cd work
              . build/envsetup.sh &&lunch omni_$DEVICE-eng &&export ALLOW_MISSING_DEPENDENCIES=true && mka $TARGET
             
       - name: Release recovery image
         uses: softprops/action-gh-release@v1
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
          tag_name: TWRP_10.0
          name: TWRP-KD7
          files: | 
            work/out/target/product/KD7/recovery.img
